package com.loanapi.model;

public enum LoanApiErrorCode {

    NOT_LOGGED_IN,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    CREDIT_LIMIT_EXCEEDED,
    INTEREST_RATE_EXCEEDED,
    NO_LOAN_INSTALLMENTS_FOUND,
    LOAN_NOT_FOUND,
    WRONG_AMOUNT, USER_NOT_FOUND, INVALID_INSTALLMENT_OPTION
}

